name: Trigger auto deployment for chatwithdocs

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/chatwithdocs-AutoDeployTrigger-d3ee5e65-b3a5-4430-ad03-c51806d7c4c3.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CHATWITHDOCS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CHATWITHDOCS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CHATWITHDOCS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: chatwithdocsc804f6.azurecr.io
          registryUsername: ${{ secrets.CHATWITHDOCS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CHATWITHDOCS_REGISTRY_PASSWORD }}
          containerAppName: chatwithdocs
          resourceGroup: chatwithdocs
          imageToBuild: chatwithdocsc804f6.azurecr.io/chatwithdocs:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


